spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5699}/${POSTGRES_DATABASE:cherry}
    username: ${POSTGRES_USER_NAME:cherry}
    password: ${POSTGRES_PASSWORD:cherry}
  jpa:
    open-in-view: 'true'
    properties:
      hibernate:
        enable_lazy_load_no_trans: 'true'
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: 'true'
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: create
  application:
    name: demo-project
server:
  port: 8081

